services:
  postgres:
    image: postgres:15
    container_name: logs_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: logs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: logs_redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: logs_api
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/logs_db
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:10000"

  worker:
    build: .
    container_name: logs_worker
    depends_on:
      - postgres
      - redis
    command: ["python", "-u", "worker.py"]
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/logs_db
      REDIS_URL: redis://redis:6379/0

  # 🔥 NUEVO: alert worker separado
  alert_worker:
    build: .
    container_name: logs_alert_worker
    depends_on:
      - postgres
      - redis
    command: ["python", "-u", "alert_worker.py"]
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/logs_db
      REDIS_URL: redis://redis:6379/0

volumes:
  postgres_data: